server:
  port: 8080

spring:
  datasource:
    username: root
    password: ertyu53f!@#dsfgfdg
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.springframework: ERROR
    searchengine: INFO


indexing-settings:
  sites:
    - url: https://skillbox.ru/
      name: Skillbox
    - url: http://radiomv.ru/
      name: Radiomv


connection-settings:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
  referer: https://www.google.com